### ISSUE TITLE
Make Eternal Singularity recipe more reasonable

### ISSUE THREAD

**Issue by ghost** [Ghalid/BIKES6#12]
With the addition of AOBD singularities, it might be a little _too_ hard to get the Eternal Singularity. One of the biggest issues may be the addition of the Extra Planets/Galacticraft metals - especially since Extra Planets dimlets are blacklisted, the only feasible way to make a singularity would be to setup a quarry at every single planet, and even then this would be quite slow.

**Is the current recipe a feasible one for the SMP, and how should we change it, if at all?**

---
Personally, I believe that AOBD singularities should stay, with the exception of singularities from Galacticraft/Extra Planets, which should be removed from the recipe. However, I'm looking for more feedback and open to other ideas.

**Comment by jamzss** [comment]
I'm in agreement on removing the ExtraPlanets singularities, because the ores are quite difficult to gather in large quantities and all EP dimets have been disabled. 

We could also experiment with this in conjunction with tweaking the amount of blocks required to make a singularity in order to balance the difficulty.

**Comment by ghost** [comment]
Extra Planets singularities are disabled. Reopen if you want to entertain the idea of changing block requirements for singularities.
